---
  0 debug pnpm:scope: 
    selected: 1
    workspacePrefix: null
  1 info pnpm: 
    message: "A store server is running. All store manipulations are delegated to it."
    prefix: "/app"
  2 error pnpm: 
    message: 
      code: "EJSONPARSE"
      file: "/app/package.json"
    err: 
      name: "Error"
      message: "Failed to parse json\nUnexpected number in JSON at position 512 while parsing '{\n  \"name\": \"gways\",\n  \"version\": \"1.0.0'"
      code: "EJSONPARSE"
      stack: "Error: Failed to parse json\nUnexpected number in JSON at position 512 while parsing '{\n  \"name\": \"gways\",\n  \"version\": \"1.0.0'\n    at parseError (/opt/nvm/versions/node/v10.23.0/lib/node_modules/pnpm/lib/node_modules/read-package-json/read-json.js:452:11)\n    at parseJson (/opt/nvm/versions/node/v10.23.0/lib/node_modules/pnpm/lib/node_modules/read-package-json/read-json.js:104:26)\n    at /opt/nvm/versions/node/v10.23.0/lib/node_modules/pnpm/lib/node_modules/read-package-json/read-json.js:51:5\n    at /opt/nvm/versions/node/v10.23.0/lib/node_modules/pnpm/lib/node_modules/graceful-fs/graceful-fs.js:90:16\n    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)"
